/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 0.2.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { useCallback } from 'react';

import type { UserDTO } from '../../model';

import { useCustomClient } from '../../custom-client';
import type { ErrorType } from '../../custom-client';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Creates a new user from the given DTO.
 */
export const useCurrentUserHook = () => {
  const currentUser = useCustomClient<UserDTO>();

  return useCallback(
    (signal?: AbortSignal) => {
      return currentUser({
        url: `/api/v1/current_user`,
        method: 'GET',
        signal,
      });
    },
    [currentUser]
  );
};

export const getCurrentUserQueryKey = () => {
  return [`/api/v1/current_user`] as const;
};

export const useCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useCurrentUserHook>>>,
  TError = ErrorType<void>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useCurrentUserHook>>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCurrentUserQueryKey();

  const currentUser = useCurrentUserHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useCurrentUserHook>>>
  > = ({ signal }) => currentUser(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useCurrentUserHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CurrentUserQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useCurrentUserHook>>>
>;
export type CurrentUserQueryError = ErrorType<void>;

/**
 * @summary Creates a new user from the given DTO.
 */

export function useCurrentUser<
  TData = Awaited<ReturnType<ReturnType<typeof useCurrentUserHook>>>,
  TError = ErrorType<void>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useCurrentUserHook>>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = useCurrentUserQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Returns a list of a users registered in the system. Needs a bearer token to track
who requested it.
 */
export const useGetUsersHook = () => {
  const getUsers = useCustomClient<UserDTO[]>();

  return useCallback(
    (signal?: AbortSignal) => {
      return getUsers({ url: `/api/v1/users`, method: 'GET', signal });
    },
    [getUsers]
  );
};

export const getGetUsersQueryKey = () => {
  return [`/api/v1/users`] as const;
};

export const useGetUsersQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetUsersHook>>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetUsersHook>>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersQueryKey();

  const getUsers = useGetUsersHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetUsersHook>>>
  > = ({ signal }) => getUsers(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetUsersHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUsersQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetUsersHook>>>
>;
export type GetUsersQueryError = ErrorType<unknown>;

/**
 * @summary Returns a list of a users registered in the system. Needs a bearer token to track
who requested it.
 */

export function useGetUsers<
  TData = Awaited<ReturnType<ReturnType<typeof useGetUsersHook>>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetUsersHook>>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = useGetUsersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
