/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 1.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { useCallback } from 'react';

import type {
  NewPotTemplateDTO,
  PotTemplateDTO,
  UserListDTO,
} from '../../model';

import { useCustomClient } from '../../custom-client';
import type { ErrorType, BodyType } from '../../custom-client';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Gets a list of all pot templates that the bearer is owning.
 */
export const useGetPotTemplatesHook = () => {
  const getPotTemplates = useCustomClient<PotTemplateDTO[]>();

  return useCallback(
    (signal?: AbortSignal) => {
      return getPotTemplates({
        url: `/api/v1/template`,
        method: 'GET',
        signal,
      });
    },
    [getPotTemplates]
  );
};

export const getGetPotTemplatesQueryKey = () => {
  return [`/api/v1/template`] as const;
};

export const useGetPotTemplatesQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetPotTemplatesHook>>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetPotTemplatesHook>>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPotTemplatesQueryKey();

  const getPotTemplates = useGetPotTemplatesHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetPotTemplatesHook>>>
  > = ({ signal }) => getPotTemplates(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetPotTemplatesHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPotTemplatesQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetPotTemplatesHook>>>
>;
export type GetPotTemplatesQueryError = ErrorType<unknown>;

/**
 * @summary Gets a list of all pot templates that the bearer is owning.
 */

export function useGetPotTemplates<
  TData = Awaited<ReturnType<ReturnType<typeof useGetPotTemplatesHook>>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetPotTemplatesHook>>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = useGetPotTemplatesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Creates a pot template from the given DTO for the bearer.
 */
export const useCreatePotTemplateHook = () => {
  const createPotTemplate = useCustomClient<PotTemplateDTO>();

  return useCallback(
    (newPotTemplateDTO: BodyType<NewPotTemplateDTO>, signal?: AbortSignal) => {
      return createPotTemplate({
        url: `/api/v1/template`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: newPotTemplateDTO,
        signal,
      });
    },
    [createPotTemplate]
  );
};

export const useCreatePotTemplateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useCreatePotTemplateHook>>>,
    TError,
    { data: BodyType<NewPotTemplateDTO> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof useCreatePotTemplateHook>>>,
  TError,
  { data: BodyType<NewPotTemplateDTO> },
  TContext
> => {
  const mutationKey = ['createPotTemplate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const createPotTemplate = useCreatePotTemplateHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof useCreatePotTemplateHook>>>,
    { data: BodyType<NewPotTemplateDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return createPotTemplate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePotTemplateMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useCreatePotTemplateHook>>>
>;
export type CreatePotTemplateMutationBody = BodyType<NewPotTemplateDTO>;
export type CreatePotTemplateMutationError = ErrorType<unknown>;

/**
 * @summary Creates a pot template from the given DTO for the bearer.
 */
export const useCreatePotTemplate = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useCreatePotTemplateHook>>>,
    TError,
    { data: BodyType<NewPotTemplateDTO> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof useCreatePotTemplateHook>>>,
  TError,
  { data: BodyType<NewPotTemplateDTO> },
  TContext
> => {
  const mutationOptions = useCreatePotTemplateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Deletes the given template if the user is the owner of the template.
 */
export const useDeletePotTemplateHook = () => {
  const deletePotTemplate = useCustomClient<void>();

  return useCallback(
    (templateId: number) => {
      return deletePotTemplate({
        url: `/api/v1/template/${templateId}`,
        method: 'DELETE',
      });
    },
    [deletePotTemplate]
  );
};

export const useDeletePotTemplateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useDeletePotTemplateHook>>>,
    TError,
    { templateId: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof useDeletePotTemplateHook>>>,
  TError,
  { templateId: number },
  TContext
> => {
  const mutationKey = ['deletePotTemplate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const deletePotTemplate = useDeletePotTemplateHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof useDeletePotTemplateHook>>>,
    { templateId: number }
  > = (props) => {
    const { templateId } = props ?? {};

    return deletePotTemplate(templateId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePotTemplateMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useDeletePotTemplateHook>>>
>;

export type DeletePotTemplateMutationError = ErrorType<void>;

/**
 * @summary Deletes the given template if the user is the owner of the template.
 */
export const useDeletePotTemplate = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useDeletePotTemplateHook>>>,
    TError,
    { templateId: number },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof useDeletePotTemplateHook>>>,
  TError,
  { templateId: number },
  TContext
> => {
  const mutationOptions = useDeletePotTemplateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Adds the given users to the given template if the calling user is the owner of the template.
 */
export const useAddUsersToTemplateHook = () => {
  const addUsersToTemplate = useCustomClient<void>();

  return useCallback(
    (templateId: number, userListDTO: BodyType<UserListDTO>) => {
      return addUsersToTemplate({
        url: `/api/v1/template/${templateId}/users/add`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: userListDTO,
      });
    },
    [addUsersToTemplate]
  );
};

export const useAddUsersToTemplateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useAddUsersToTemplateHook>>>,
    TError,
    { templateId: number; data: BodyType<UserListDTO> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof useAddUsersToTemplateHook>>>,
  TError,
  { templateId: number; data: BodyType<UserListDTO> },
  TContext
> => {
  const mutationKey = ['addUsersToTemplate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const addUsersToTemplate = useAddUsersToTemplateHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof useAddUsersToTemplateHook>>>,
    { templateId: number; data: BodyType<UserListDTO> }
  > = (props) => {
    const { templateId, data } = props ?? {};

    return addUsersToTemplate(templateId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddUsersToTemplateMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useAddUsersToTemplateHook>>>
>;
export type AddUsersToTemplateMutationBody = BodyType<UserListDTO>;
export type AddUsersToTemplateMutationError = ErrorType<void>;

/**
 * @summary Adds the given users to the given template if the calling user is the owner of the template.
 */
export const useAddUsersToTemplate = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useAddUsersToTemplateHook>>>,
    TError,
    { templateId: number; data: BodyType<UserListDTO> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof useAddUsersToTemplateHook>>>,
  TError,
  { templateId: number; data: BodyType<UserListDTO> },
  TContext
> => {
  const mutationOptions = useAddUsersToTemplateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Removes the given users from the given template if the calling user is the owner of the template.
 */
export const useRemoveUsersFromTemplateHook = () => {
  const removeUsersFromTemplate = useCustomClient<void>();

  return useCallback(
    (templateId: number, userListDTO: BodyType<UserListDTO>) => {
      return removeUsersFromTemplate({
        url: `/api/v1/template/${templateId}/users/remove`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: userListDTO,
      });
    },
    [removeUsersFromTemplate]
  );
};

export const useRemoveUsersFromTemplateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useRemoveUsersFromTemplateHook>>>,
    TError,
    { templateId: number; data: BodyType<UserListDTO> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof useRemoveUsersFromTemplateHook>>>,
  TError,
  { templateId: number; data: BodyType<UserListDTO> },
  TContext
> => {
  const mutationKey = ['removeUsersFromTemplate'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const removeUsersFromTemplate = useRemoveUsersFromTemplateHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof useRemoveUsersFromTemplateHook>>>,
    { templateId: number; data: BodyType<UserListDTO> }
  > = (props) => {
    const { templateId, data } = props ?? {};

    return removeUsersFromTemplate(templateId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveUsersFromTemplateMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useRemoveUsersFromTemplateHook>>>
>;
export type RemoveUsersFromTemplateMutationBody = BodyType<UserListDTO>;
export type RemoveUsersFromTemplateMutationError = ErrorType<void>;

/**
 * @summary Removes the given users from the given template if the calling user is the owner of the template.
 */
export const useRemoveUsersFromTemplate = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useRemoveUsersFromTemplateHook>>>,
    TError,
    { templateId: number; data: BodyType<UserListDTO> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof useRemoveUsersFromTemplateHook>>>,
  TError,
  { templateId: number; data: BodyType<UserListDTO> },
  TContext
> => {
  const mutationOptions = useRemoveUsersFromTemplateMutationOptions(options);

  return useMutation(mutationOptions);
};
