/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { useCallback } from 'react';

import { useCustomClient } from '../../custom-client';
import type { ErrorType } from '../../custom-client';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary HealthCheck Url
 */
export const useHealthCheckHook = () => {
  const healthCheck = useCustomClient<string>();

  return useCallback(
    (signal?: AbortSignal) => {
      return healthCheck({ url: `/api/v1/health`, method: 'GET', signal });
    },
    [healthCheck]
  );
};

export const getHealthCheckQueryKey = () => {
  return [`/api/v1/health`] as const;
};

export const useHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const healthCheck = useHealthCheckHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>
  > = ({ signal }) => healthCheck(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary HealthCheck Url
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useHealthCheckHook>>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = useHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
