ALTER TABLE pots ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
ALTER TABLE pots ADD COLUMN archived_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE pots ADD COLUMN archived BOOLEAN NOT NULL DEFAULT false;