/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 0.2.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { useCallback } from 'react';

import type { ExpenseDTO, PayExpenseDTO } from '../../model';

import { useCustomClient } from '../../custom-client';
import type { ErrorType, BodyType } from '../../custom-client';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Gets the expense with the given id. Returns 404 if no expense with the given id exists
or the bearer has no access to it.
 */
export const useGetExpenseByIdHook = () => {
  const getExpenseById = useCustomClient<ExpenseDTO>();

  return useCallback(
    (expenseId: number, signal?: AbortSignal) => {
      return getExpenseById({
        url: `/api/v1/expenses/${expenseId}`,
        method: 'GET',
        signal,
      });
    },
    [getExpenseById]
  );
};

export const getGetExpenseByIdQueryKey = (expenseId: number) => {
  return [`/api/v1/expenses/${expenseId}`] as const;
};

export const useGetExpenseByIdQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetExpenseByIdHook>>>,
  TError = ErrorType<void>
>(
  expenseId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<ReturnType<typeof useGetExpenseByIdHook>>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetExpenseByIdQueryKey(expenseId);

  const getExpenseById = useGetExpenseByIdHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetExpenseByIdHook>>>
  > = ({ signal }) => getExpenseById(expenseId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!expenseId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetExpenseByIdHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetExpenseByIdQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetExpenseByIdHook>>>
>;
export type GetExpenseByIdQueryError = ErrorType<void>;

/**
 * @summary Gets the expense with the given id. Returns 404 if no expense with the given id exists
or the bearer has no access to it.
 */

export function useGetExpenseById<
  TData = Awaited<ReturnType<ReturnType<typeof useGetExpenseByIdHook>>>,
  TError = ErrorType<void>
>(
  expenseId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<ReturnType<typeof useGetExpenseByIdHook>>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = useGetExpenseByIdQueryOptions(expenseId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Pays the expense with the given `expense_id` if the user has access to it.
 */
export const usePayExpenseHook = () => {
  const payExpense = useCustomClient<ExpenseDTO>();

  return useCallback(
    (expenseId: number, payExpenseDTO: BodyType<PayExpenseDTO>) => {
      return payExpense({
        url: `/api/v1/expenses/${expenseId}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: payExpenseDTO,
      });
    },
    [payExpense]
  );
};

export const usePayExpenseMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof usePayExpenseHook>>>,
    TError,
    { expenseId: number; data: BodyType<PayExpenseDTO> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof usePayExpenseHook>>>,
  TError,
  { expenseId: number; data: BodyType<PayExpenseDTO> },
  TContext
> => {
  const mutationKey = ['payExpense'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const payExpense = usePayExpenseHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof usePayExpenseHook>>>,
    { expenseId: number; data: BodyType<PayExpenseDTO> }
  > = (props) => {
    const { expenseId, data } = props ?? {};

    return payExpense(expenseId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PayExpenseMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof usePayExpenseHook>>>
>;
export type PayExpenseMutationBody = BodyType<PayExpenseDTO>;
export type PayExpenseMutationError = ErrorType<void>;

/**
 * @summary Pays the expense with the given `expense_id` if the user has access to it.
 */
export const usePayExpense = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof usePayExpenseHook>>>,
    TError,
    { expenseId: number; data: BodyType<PayExpenseDTO> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof usePayExpenseHook>>>,
  TError,
  { expenseId: number; data: BodyType<PayExpenseDTO> },
  TContext
> => {
  const mutationOptions = usePayExpenseMutationOptions(options);

  return useMutation(mutationOptions);
};
