/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 0.3.0
 */
import type { CurrencyDTO } from './currencyDTO';
import type { SplitDTO } from './splitDTO';

/**
 * DTO used when working with existing Expenses.
 */
export interface ExpenseDTO {
  currency: CurrencyDTO;
  description: string;
  id: number;
  owner_id: string;
  pot_id: number;
  splits: SplitDTO[];
  /** If negative: you have to pay `owner_id` this amount of money, otherwise
you can expect others to pay you the given amount. */
  sum: number;
}
