/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 1.1.0
 */

/**
 * DTO representing a new currency.
 */
export interface NewCurrencyDTO {
  name: string;
  symbol: string;
}
