/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 0.3.0
 */
import type { NewSplitDTO } from './newSplitDTO';

/**
 * DTO used when creating a new expense for the given pot.
 */
export interface NewExpenseDTO {
  currency_id: number;
  /** @maxLength 24 */
  description: string;
  splits: NewSplitDTO[];
}
