/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 0.2.0
 */
import type { SplitDTO } from './splitDTO';

/**
 * DTO used when creating a new expense for the given pot.
 */
export interface NewExpenseDTO {
  currency_id: number;
  description: string;
  splits: SplitDTO[];
}
