/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 0.2.0
 */

/**
 * DTO used when creating new Splits for expenses.
 */
export interface NewSplitDTO {
  amount: number;
  user_id: string;
}
