/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 0.3.0
 */

/**
 * DTO used to update an expense
 */
export interface PayExpenseDTO {
  sum_paid: number;
}
