/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 1.0.0
 */
import type { PotDTOArchivedAt } from './potDTOArchivedAt';
import type { CurrencyDTO } from './currencyDTO';
import type { UserDTO } from './userDTO';

/**
 * DTO used when working with existing Pots.
 */
export interface PotDTO {
  archived: boolean;
  archived_at?: PotDTOArchivedAt;
  created_at: string;
  default_currency: CurrencyDTO;
  id: number;
  name: string;
  /** Indicates the amount of money, the user is owed or owes others. If positive, other users
need to pay that amount to the user. If negative, the user has to pay the given amount. */
  net_balance: number;
  owner_id: string;
  users: UserDTO[];
}
