/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 0.2.0
 */
import type { CurrencyDTO } from './currencyDTO';
import type { UserDTO } from './userDTO';

/**
 * DTO used when working with existing Pots.
 */
export interface PotDTO {
  default_currency: CurrencyDTO;
  id: number;
  name: string;
  owner_id: string;
  users: UserDTO[];
}
