/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 1.1.0
 */
import type { CurrencyDTO } from './currencyDTO';
import type { UserDTO } from './userDTO';

export interface PotTemplateDTO {
  /** The example shows how a cron expression must look that expresses "At 12:00 AM, on day 1 of the month"
I recommend using tools like https://crontab.cronhub.io to generate and validate a cron expression.
Expense-Tracker uses the local timezone to make it easier for the user to think in their local timezone. */
  cron_expression: string;
  default_currency: CurrencyDTO;
  id: number;
  name: string;
  owner: UserDTO;
  users: UserDTO[];
}
