/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 0.3.0
 */

/**
 * DTO used when working with splits.
 */
export interface SplitDTO {
  amount: number;
  /** Is `true` by default, if the Split's `user_id` == the expenses `owner_id`! Otherwise
`false`. This is because the owner of an expense has already paid their part! */
  is_paid: boolean;
  user_id: string;
}
