/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 0.2.18
 */

/**
 * The DTO representing a user from DB.
 */
export interface UserDTO {
  name: string;
  uuid: string;
}
