/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 0.2.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface AddUserToPotDTO {
  user_id: string;
}

/**
 * DTO representing a currency.
 */
export interface CurrencyDTO {
  id: number;
  name: string;
  symbol: string;
}

/**
 * DTO used when working with existing Expenses.
 */
export interface ExpenseDTO {
  currency: CurrencyDTO;
  description: string;
  id: number;
  owner_id: string;
  pot_id: number;
  splits: SplitDTO[];
  /** If negative: you have to pay `owner_id` this amount of money, otherwise
you can expect others to pay you the given amount. */
  sum: number;
}

/**
 * DTO representing a new currency.
 */
export interface NewCurrencyDTO {
  name: string;
  symbol: string;
}

/**
 * DTO used when creating a new expense for the given pot.
 */
export interface NewExpenseDTO {
  currency_id: number;
  description: string;
  splits: SplitDTO[];
}

/**
 * DTO used when creating a new Pot.
 */
export interface NewPotDTO {
  default_currency_id: number;
  name: string;
}

/**
 * DTO used to update an expense
 */
export interface PayExpenseDTO {
  sum_paid: number;
}

/**
 * DTO used when working with existing Pots.
 */
export interface PotDTO {
  default_currency: CurrencyDTO;
  id: number;
  name: string;
  owner_id: string;
  users: UserDTO[];
}

export interface RemoveUserFromPotDTO {
  user_id: string;
}

/**
 * DTO used when working with splits.
 */
export interface SplitDTO {
  amount: number;
  /** Is `true` by default, if the Split's `user_id` == the expenses `owner_id`! Otherwise
`false`. This is because the owner of an expense has already paid their part! */
  is_paid: boolean;
  user_id: string;
}

/**
 * The DTO representing a user from DB.
 */
export interface UserDTO {
  name: string;
  uuid: string;
}

/**
 * @summary Gets a list of all currently known currencies.
 */
export const getCurrencies = <TData = AxiosResponse<CurrencyDTO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:3001/api/v1/currencies`,options
    );
  }

/**
 * @summary Creates a new currency, if symbol is not yet in use.
 */
export const createCurrency = <TData = AxiosResponse<NewCurrencyDTO>>(
    newCurrencyDTO: NewCurrencyDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:3001/api/v1/currencies`,
      newCurrencyDTO,options
    );
  }

/**
 * @summary Creates a new user from the given DTO.
 */
export const currentUser = <TData = AxiosResponse<UserDTO>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:3001/api/v1/current_user`,options
    );
  }

/**
 * @summary Gets the expense with the given id. Returns 404 if no expense with the given id exists
or the bearer has no access to it.
 */
export const getExpenseById = <TData = AxiosResponse<ExpenseDTO>>(
    expenseId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:3001/api/v1/expenses/${expenseId}`,options
    );
  }

/**
 * @summary Pays the expense with the given `expense_id` if the user has access to it.
 */
export const payExpense = <TData = AxiosResponse<ExpenseDTO>>(
    expenseId: number,
    payExpenseDTO: PayExpenseDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3001/api/v1/expenses/${expenseId}`,
      payExpenseDTO,options
    );
  }

/**
 * @summary HealthCheck Url
 */
export const healthCheck = <TData = AxiosResponse<string>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:3001/api/v1/health`,options
    );
  }

/**
 * @summary Gets the list of all pots the bearer can view.
 */
export const getPots = <TData = AxiosResponse<PotDTO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:3001/api/v1/pots`,options
    );
  }

/**
 * @summary Creates a pot from the given DTO for the bearer.
 */
export const createPot = <TData = AxiosResponse<PotDTO>>(
    newPotDTO: NewPotDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:3001/api/v1/pots`,
      newPotDTO,options
    );
  }

/**
 * @summary Gets the sum of all expenses for the given user of the given pot.
 */
export const getPotExpenses = <TData = AxiosResponse<ExpenseDTO[]>>(
    potId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:3001/api/v1/pots/${potId}`,options
    );
  }

/**
 * @summary Adds the given user to the pot, if Bearer is the owner of that pot.
 */
export const addUserToPot = <TData = AxiosResponse<void>>(
    potId: number,
    addUserToPotDTO: AddUserToPotDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3001/api/v1/pots/${potId}`,
      addUserToPotDTO,options
    );
  }

/**
 * @summary Adds a new expense in the name of the user from the Bearer token to the pot with the given
pot_id if it exists.
 */
export const addExpense = <TData = AxiosResponse<ExpenseDTO>>(
    potId: number,
    newExpenseDTO: NewExpenseDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `http://localhost:3001/api/v1/pots/${potId}`,
      newExpenseDTO,options
    );
  }

/**
 * @summary Deletes the given pot if it does not contain any outstanding expenses and the caller
is the pot's owner.
 */
export const deletePot = <TData = AxiosResponse<void>>(
    potId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `http://localhost:3001/api/v1/pots/${potId}`,options
    );
  }

/**
 * @summary Removes the given user from the pot, if Bearer is the owner of that pot.
 */
export const removeUserFromPot = <TData = AxiosResponse<void>>(
    potId: number,
    removeUserFromPotDTO: RemoveUserFromPotDTO, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3001/api/v1/pots/${potId}/remove_user`,
      removeUserFromPotDTO,options
    );
  }

/**
 * @summary Returns a list of a users registered in the system. Needs a bearer token to track
who requested it.
 */
export const getUsers = <TData = AxiosResponse<UserDTO[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:3001/api/v1/users`,options
    );
  }

export type GetCurrenciesResult = AxiosResponse<CurrencyDTO[]>
export type CreateCurrencyResult = AxiosResponse<NewCurrencyDTO>
export type CurrentUserResult = AxiosResponse<UserDTO>
export type GetExpenseByIdResult = AxiosResponse<ExpenseDTO>
export type PayExpenseResult = AxiosResponse<ExpenseDTO>
export type HealthCheckResult = AxiosResponse<string>
export type GetPotsResult = AxiosResponse<PotDTO[]>
export type CreatePotResult = AxiosResponse<PotDTO>
export type GetPotExpensesResult = AxiosResponse<ExpenseDTO[]>
export type AddUserToPotResult = AxiosResponse<void>
export type AddExpenseResult = AxiosResponse<ExpenseDTO>
export type DeletePotResult = AxiosResponse<void>
export type RemoveUserFromPotResult = AxiosResponse<void>
export type GetUsersResult = AxiosResponse<UserDTO[]>
