[oidc]
issuer_url = "http://127.0.0.1:8001/realms/local" # only adjust port
audience = "expense-tracker"

[expense_tracker]
port = 3001
db_connection_string = "postgres://et:localpassword@localhost/expense_tracker"
cors_url="http://127.0.0.1:3000"
