/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * expense_tracker
 * A REST Api that offers various endpoints for handling shared expenses.
 * OpenAPI spec version: 0.3.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { useCallback } from 'react';

import type { CurrencyDTO, NewCurrencyDTO } from '../../model';

import { useCustomClient } from '../../custom-client';
import type { ErrorType, BodyType } from '../../custom-client';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Gets a list of all currently known currencies.
 */
export const useGetCurrenciesHook = () => {
  const getCurrencies = useCustomClient<CurrencyDTO[]>();

  return useCallback(
    (signal?: AbortSignal) => {
      return getCurrencies({
        url: `/api/v1/currencies`,
        method: 'GET',
        signal,
      });
    },
    [getCurrencies]
  );
};

export const getGetCurrenciesQueryKey = () => {
  return [`/api/v1/currencies`] as const;
};

export const useGetCurrenciesQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetCurrenciesHook>>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetCurrenciesHook>>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrenciesQueryKey();

  const getCurrencies = useGetCurrenciesHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetCurrenciesHook>>>
  > = ({ signal }) => getCurrencies(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetCurrenciesHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCurrenciesQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetCurrenciesHook>>>
>;
export type GetCurrenciesQueryError = ErrorType<unknown>;

/**
 * @summary Gets a list of all currently known currencies.
 */

export function useGetCurrencies<
  TData = Awaited<ReturnType<ReturnType<typeof useGetCurrenciesHook>>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetCurrenciesHook>>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = useGetCurrenciesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Creates a new currency, if symbol is not yet in use.
 */
export const useCreateCurrencyHook = () => {
  const createCurrency = useCustomClient<NewCurrencyDTO>();

  return useCallback(
    (newCurrencyDTO: BodyType<NewCurrencyDTO>, signal?: AbortSignal) => {
      return createCurrency({
        url: `/api/v1/currencies`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: newCurrencyDTO,
        signal,
      });
    },
    [createCurrency]
  );
};

export const useCreateCurrencyMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useCreateCurrencyHook>>>,
    TError,
    { data: BodyType<NewCurrencyDTO> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof useCreateCurrencyHook>>>,
  TError,
  { data: BodyType<NewCurrencyDTO> },
  TContext
> => {
  const mutationKey = ['createCurrency'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const createCurrency = useCreateCurrencyHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof useCreateCurrencyHook>>>,
    { data: BodyType<NewCurrencyDTO> }
  > = (props) => {
    const { data } = props ?? {};

    return createCurrency(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCurrencyMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useCreateCurrencyHook>>>
>;
export type CreateCurrencyMutationBody = BodyType<NewCurrencyDTO>;
export type CreateCurrencyMutationError = ErrorType<void>;

/**
 * @summary Creates a new currency, if symbol is not yet in use.
 */
export const useCreateCurrency = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useCreateCurrencyHook>>>,
    TError,
    { data: BodyType<NewCurrencyDTO> },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof useCreateCurrencyHook>>>,
  TError,
  { data: BodyType<NewCurrencyDTO> },
  TContext
> => {
  const mutationOptions = useCreateCurrencyMutationOptions(options);

  return useMutation(mutationOptions);
};
